INSERT INTO Players (name) VALUES ('РАФАЭЛЬ НАДАЛЬ');
INSERT INTO Players (name) VALUES ('РОДЖЕР ФЕДЕРЕР');
INSERT INTO Players (name) VALUES ('НОВАК ДЖОКОВИЧ');
INSERT INTO Players (name) VALUES ('ДАНИИЛ МЕДВЕДЕВ');
INSERT INTO Players (name) VALUES ('КАРЛОС АЛЬКАРАС');
INSERT INTO Players (name) VALUES ('БЬОРН БОРГ');
INSERT INTO Players (name) VALUES ('АНДРЕ АГАССИ');
INSERT INTO Players (name) VALUES ('АНДРЕЙ РУБЛЁВ');
INSERT INTO Players (name) VALUES ('ПИТ САМПРАС');
INSERT INTO Players (name) VALUES ('ЭНДИ РОДДИК');
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (1, 2, 2);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (2, 3, 2);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (3, 4, 4);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (4, 5, 4);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (5, 6, 5);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (6, 7, 6);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (7, 8, 8);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (8, 9, 8);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (9, 10, 10);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (2, 9, 2);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (2, 7, 2);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (4, 9, 4);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (4, 8, 8);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (4, 6, 4);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (3, 4, 3);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (3, 5, 3);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (3, 7, 3);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (2, 7, 2);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (2, 5, 2);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (6, 2, 2);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (9, 3, 3);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (1, 3, 1);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (1, 6, 1);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (6, 1, 1);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (9, 1, 1);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (1, 3, 1);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (1, 7, 1);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (1, 8, 1);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (1, 5, 1);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (6, 4, 1);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (10, 1, 1);
INSERT INTO Matches (player1_id, player2_id, winner_id) VALUES (1, 10, 1);